//AUTOGENERATED FILE - DO NOT EDIT
#ifndef __MAGICDATA_CONSTANTS_H__
#define __MAGICDATA_CONSTANTS_H__

/*
This file is part of fsfuzz.

(c) 2023 by kittennbfive

https://github.com/kittennbfive

AGPLv3+ and NO WARRANTY!
*/

#define NB_ENTRIES_MAGIC 52
#define NB_TESTS_MAX 47
#define NB_LEVELS_MAX 7
#define NB_BYTES_MAX 36

#endif
